### ISSUE TITLE
ProfileId koppelen aan accountObject

### ISSUE THREAD

**Issue by KaivWezel** [DeefDeMeef/blok-tech-team4#14]
Het lukt nu om het profileId op te slaan in het accountObject. Wanneer ik relog werkt de check ook om te kijken of hij een profielId heeft. Alleen bij het reloggen slaat hij het object opnieuw op o.i.d., waardoor het profileId verdwijnt:

`1ste keer  :  register -> login -> (geen profileId) --redirect--> createProfile -> profilepagina -> logout;`
`2de keer  :  login -> (profileId aanwezig) --redirect--> profilepagina; ` _In deze stap slaat hij het account opnieuw op waardoor het profileId weg is_`

**Comment by DeefDeMeef** [comment]
Gefixt met Rijk en Adriaan
