### ISSUE TITLE
basis formulier voor de eigenschappen van een profiel

### ISSUE THREAD

**Issue by KaivWezel** [DeefDeMeef/blok-tech-team4#6]
Met het basis formulier wordt duidelijk waar op gefilterd kan worden bij het liken van profielen.

Ga uit van:
- Leeftijd
- Sport

**Comment by sarahverkade** [comment]
wat bedoel je precies met een basisformulier in de vorm van documentatie?

**Comment by KaivWezel** [comment]
Het registratie formulier dat jij zojuist hebt gepost in ons teamskanaal :)
